file:
  upload-dir: ./uploads #사진폴더 -> 파일이 어디/얼마까지 저장될지 서버가 알아야 함.

server:
  port: 8080

jwt:
  secret: default-secret-key
  access-ttl: PT10M
  refresh-ttl: P13D
  issuer: your-service

# Swagger UI 설정 제거 - OpenApiConfig 삭제로 인해 불필요
  

spring:
  datasource:
    url: jdbc:mysql://144.24.80.209:3306/safestargram?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: safestargram
    password: safetyworld
  servlet: #사진폴더 -> 파일이 어디/얼마까지 저장될지 서버가 알아야 함.
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/safestargram?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
#    username: root
#    password: 12341234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#spring:
#  profiles:
#    active: dev
api:
  base-url: http://localhost:8080